require "capistrano/setup"

require "capistrano/deploy"

require 'capistrano/rvm'
set :rvm_type, :user
set :rvm_ruby_version, '3.2.1'

require 'capistrano/bundler'
require 'capistrano/puma'
require 'capistrano/rails'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
